### ISSUE TITLE
[User feedback] Incoming message not appearing in inbox

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#100]
## dhis2

Username: stodd

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/

Sending a message works fine; incoming messages only go to my email and not the inbox

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1594064164298405645.png )

**Comment by adrianq** [comment]
Not an issue this is the expected behaviour
