### ISSUE TITLE
[User feedback] No data values appearing in dashboard

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#108]
## dhis2

Username: stodd

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/dashboard/kLwDBFpigz9

Despite there being actual and target data values inputted into the system, no values are showing up in any of the dashboard tables

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1594150472608840562.png )

**Comment by adrianq** [comment]
Solved in 0.3.1
