### ISSUE TITLE
[User feedback] funder default to SP IHQ US

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#11]
## dhis2

Username: topelt

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
- Platform: Win32

## User report
URL: http://dev2.eyeseetea.com:8087/api/apps/Project-Monitoring-App/index.html#/projects/new

## Summary
since most projects are IHQ funded, user should not be forced to scroll down or search each. can it be the top option or an auto default selection?
## Expected results

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1580849343592349051.png )

**Comment by adrianq** [comment]
Duplicated issues:
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/31
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/34
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/53
