### ISSUE TITLE
[User feedback] Delay in data updating in dashboard

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#118]
## dhis2

Username: stodd

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/dashboard/kLwDBFpigz9

Though I have inputted target/actual values nearly 24 hours ago, they are still not appearing in the dashboard.

When I first starting inputting values a few days ago, they did not appear in my dashboard until after Justin had opened the dashboard on his device (nearly 3 days later.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1594390410479434122.png )

**Comment by adrianq** [comment]
Solved in 0.3.1
