### ISSUE TITLE
[User feedback] Kicked out of Project Creation

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#123]
## dhis2

Username: awarder

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/projects/new

I submitted feedback on a ministry indicator and after the program kicked me out of the project I was creating and sent me back to the new projects page.

## Expected results

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1594938155770458972.png )

**Comment by adrianq** [comment]
I guess it has to do with inactivity on the browser. Cannot replicate
