### ISSUE TITLE
[User feedback] Coding Apppeared

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#126]
## dhis2

Username: gharmon

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/projects/new

Hello! When I clicked to save my project, all this coding appeared below the save button.

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595439505720219262.png )

**Comment by adrianq** [comment]
We cannot reproduce this error and, unfortunately, we cannot see the coding message. It would be great if the user can let us know about the steps to reproduce or at least, copy and paste the error as a regular text.

**Comment by adrianq** [comment]
Waiting for user feedback...
