### ISSUE TITLE
[User feedback] Refine projects list

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#127]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-training.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/

If I am a user with access to only one country- I will only be able to see that one country and the projects I'm assigned to- right?

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-159543959926792807.png )

**Comment by adrianq** [comment]
Yes, in the dropdown you will only see the countries you are assigned to. See how it looks for Grace:
![image.png](https://app.gitkraken.com/api/glo/boards/5e38009c0e8c72001100f20b/attachments/5f196d4ebc186400121914ad)

However, in terms of the projects, we are showing all the projects of the country. I guess we want to show only the projects of the country assigned (step 'Username access') to the user, right? This is not how it is working at the moment.

For instance, in this case:
![image.png](https://app.gitkraken.com/api/glo/boards/5e38009c0e8c72001100f20b/attachments/5f196dbb87665c0011005907)

Grace should not be seen test-admin-bahamas as it is part of Bahamas but she has not been assigned to the project (the project was created by the admin user).
