### ISSUE TITLE
[User feedback] The Validation Rule is Not Working

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#129]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-training.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/target-values/lscg5fPMsh6

The validation rule is not working for returning beneficiaries.  The entry should not be larger than the sum of prior months (except for the first month).

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595440352796900628.png )

**Comment by adrianq** [comment]
You are right. This is a bug that is caused due to the COVID feature. We will have a look at it.
