### ISSUE TITLE
[User feedback] Food default

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#131]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-training.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/data-approval/lscg5fPMsh6

Why does the sector say "food default"?

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595440676276876923.png )

**Comment by adrianq** [comment]
@pmt This form is automatically generated by DHIS2 and we are just embedding it into the application. The logic behind that label is that DHIS2 shows the data group by sector and disaggregation 'Food New-Returning/Gender'. default, in this case, means that there is no disaggregation. This section is actually showing you the benefit indicators (no COVID-19) of the food sector... Everything can be changed but unless strictly necessary I will not customize this form as it would require a big effort.

**Comment by adrianq** [comment]
Closing it for now after discussing with @pmt
