### ISSUE TITLE
[User feedback] Executive Summary Split By Sector

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#134]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-training.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/report

We still need the executive summary to be split by sector.  I  know this was not the largest priority for pilot.  But, can we add now?

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595441301587647215.png )

**Comment by adrianq** [comment]
Duplicated of #94. I will send you a mail with the list of tasks and we can prioritize...
