### ISSUE TITLE
[User feedback] Download is Missing pieces of Information

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#135]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-training.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/report

The download of the MER is missing several columns of target to date, actual to date.  

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595441444443219174.png )

**Comment by adrianq** [comment]
I guess we added the 'to date' columns at a later stage and we forgot to add it to the excel file. Do you want to add these two columns the document as well?
