### ISSUE TITLE
[User feedback] Unable to set targets

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#137]
## dhis2

Username: vIrikefe

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.40
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/target-values/QUSnvJzsywY

The form is not loading any data to enable me input targets after creating a project.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595451247719506310.png )

**Comment by adrianq** [comment]
This is a bug. There is a problem with the permission for non-PM Admin users. We will review and fix!
