### ISSUE TITLE
[User feedback] Check box for covid disaggregation 

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#139]
## dhis2

Username: stodd

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-training.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/projects/edit/MDExbfysts4

It is unclear what the purpose of this check box is. For covid disaggregation, do you select "yes" or "no" on the right AND select this box?

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595507178072325303.png )

**Comment by adrianq** [comment]
We have agreed not to do anything for now and wait for the user feedback
