### ISSUE TITLE
[User feedback] Guidance incomplete

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#146]
## dhis2

Username: awarder

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.40
- Platform: Win32

## User report
URL: https://platform-training.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/projects/new

When I hover my mouse over this indicator I can only see the first two lines of the "guidance." There is more information for this one that is missing/not showing.

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-15955234258387502.png )

**Comment by adrianq** [comment]
@pmt we cannot see in the screenshot the specific indicator but there are some indicators displaying more than 2 lines in the guidance. Therefore, it looks like some metadata is missing in the indicator list. Assigning it to you...
