### ISSUE TITLE
[User feedback] Submit

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#148]
## dhis2

Username: bpipher

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/projects/new

## Summary
How do I submit my chosen added users? I entered pmt@samaritan.org and then it didn't show up anywhere.
## Expected results

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595526796026421269.png )

**Comment by adrianq** [comment]
Unfortunately, this feature doesn't allow to add a user by email. You will have to look by name, surname or username. If you start typing some letters the steps will suggest some possible users and user groups:
![image](https://user-images.githubusercontent.com/6850223/88384824-0ecf8380-cda5-11ea-8d3c-9b4ee5e113bd.png)
