### ISSUE TITLE
[User feedback] org unit not found

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#150]
## dhis2

Username: bpipher

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/target-values/oy9daEIO0wU

## Summary
when i try to enter data here it tells me org unit not found, but it did not do this on the previous months
## Expected results

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595534618579812882.png )

**Comment by adrianq** [comment]
We cannot reproduce the error. Not sure if this was a random error or if you are able to pass some steps to reproduce the problem?
