### ISSUE TITLE
[User feedback] actual

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#151]
## dhis2

Username: bpipher

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/actual-values/oy9daEIO0wU

## Summary
I have entered actual values for April and May, but they do not show up in the dashboard.
## Expected results

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595535055658166426.png )

**Comment by adrianq** [comment]
Dashboard seems to be showing the data properly:
![image](https://user-images.githubusercontent.com/6850223/88383852-39b8d800-cda3-11ea-848e-61f46cf5f344.png)

Perhaps the analytics were not finished yet...
