### ISSUE TITLE
[User feedback] % Achieved Total Column

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#153]
## dhis2

Username: gharmon

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/dashboard/vL9TxoMCLt2

The "total column" for this dashboard should be calculating only new people. So it should be the unique actuals divided by the unique targets. 

Right now it is calculating the sum of new and returning actuals divided by new and returning targets.
---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595598253196691789.png )

**Comment by projectmanagementteam** [comment]
Need to revise dashboards.. will document elsewhere...
