### ISSUE TITLE
[User feedback] Calculation question

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#154]
## dhis2

Username: awarder

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.40
- Platform: Win32

## User report
URL: https://platform-training.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/dashboard/ZT86GwEM0kh

I'm not sure this cell is calculating correctly. When I checked this calculation by hand I found the following for % achieved of total # of people presented with the gospel:

Total actual people (new and recurring) = 813
Total target people = 700

813/700 = 1.1614
1.1614 = 116.1%

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595601789309478926.png )

**Comment by projectmanagementteam** [comment]
We need to revise dashboards... will document elsewhere.
