### ISSUE TITLE
[User feedback] Message not delivering to my email inbox

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#157]
## dhis2

Username: gharmon

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/data-approval/UerfSiJ7vQ2

When I am on the data approval screen and click "send message," I noticed that the message appears in my inbox on platform, but it does not send to my email. I was told that it would send to my email so I just wanted to mention it here!

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595613651011574571.png )

**Comment by adrianq** [comment]
Message forwarding does not work out of the box. The user needs to go to the user setting and enable 'message email notifications'
