### ISSUE TITLE
[User feedback] Weird Computer Coding

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#158]
## dhis2

Username: awarder

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36 Edg/84.0.522.44
- Platform: Win32

## User report
URL: https://platform-training.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/projects/edit/ZT86GwEM0kh

It is weird that you allowed me to create a project but then gave me only this weird computer coding when I went to save the project. What does this mean?

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595856275561298340.png )

**Comment by adrianq** [comment]
We cannot see the error message and we cannot reproduce the error. However, this is the third time this user is reporting this error, can we please ask him the steps to reproduce the error or even better to copy&paste the error and take a regular screenshot?
