### ISSUE TITLE
[User feedback] Bulk covid 19 indicator selection

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#165]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://platform.samaritanspurse.org/api/apps/Data-Management-App/index.html#/projects/edit/S76iZVjCJoF

Can we have the bulk option here?  Clicking multiple indicators and covid applies to all.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1595961351734556306.png )

**Comment by jmatthewarnold** [comment]
I’m pretty sure that functionality is there.

Justin Arnold
SAMARITAN'S PURSE
Program Manager | Information Technology
828-588-2048 | Cell 828-406-1166 | jarnold@samaritan.org<mailto:jarnold@samaritan.org>
https://WWW.SAMARITANSPURSE.ORG <http://www.samaritanspurse.org/>
P.O. BOX 3000 | BOONE, NC 28607

**Comment by adrianq** [comment]
Yes, it seems to be there...
![image](https://user-images.githubusercontent.com/6850223/88713853-d537a900-d113-11ea-92c7-35173e80868d.png)

...unless it has to do with your browser, user or something along these lines...

**Comment by projectmanagementteam** [comment]
Done- clicked wrong button.
