### ISSUE TITLE
[Customise data entry] [User feedback] Viewing Comments

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#166]
## dhis2

Username: gharmon

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/actual-values/pNIYj3MPTRJ

Is there an easier way to view comments in a more centralized format or as a highlight on a cell? For example, if I make a comment here, it will only appear if I double click on the cell. The person viewing this wouldn't know there is a comment unless they double click on each cell to dig for the comments.

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1596035708097396309.png )

**Comment by adrianq** [comment]
Related to #168

**Comment by adrianq** [comment]
Duplicated of #221
