### ISSUE TITLE
[User feedback] Comment Box is not big enough to see items

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#167]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/target-values/vL9TxoMCLt2

The comment box is not big enough to see audit trail.  You can also not add min and max values... can this be unlocked?  

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1596044769988318321.png )

**Comment by adrianq** [comment]
Similar to https://app.gitkraken.com/glo/view/card/6367f2c92c964aca8ad80ad0418d4c46 We can discuss later on in our meeting if we want to customize this
