### ISSUE TITLE
[User feedback] Dashboard Idea- NOT URGENT

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#168]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/

Can we add a dashboard that shows the comments that were entered for values during data entry?  Or, show audit trail?  Or both?

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1596045049872161808.png )

**Comment by adrianq** [comment]
I think this is a good idea. I didn't know you plan to use the comments in DHIS2. We are actually working in something similar with WHO: displaying this kind of information in a dashboard item (similar to the charts and tables) in the dashboard. Moving to the TODO column for now - we will prioritize next week.

**Comment by adrianq** [comment]
duplicated of #221 - closing
