### ISSUE TITLE
[User feedback] Min and Max Values not removing

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#169]
## dhis2

Username: gharmon

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/target-values/pNIYj3MPTRJ

When I go to remove the minimum and maximum values, the system is slow to process that change. It doesn't automatically update.

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1596048201760742223.png )

**Comment by adrianq** [comment]
We are not supporting the min/max functionality for now. This is something that comes by default with DHIS2 but if we want to offer this feature we will have to configure it. I think there is enough on our plates so I will keep as an idea for the future. @projectmanagementteam let me know if you want to tackle this now

**Comment by projectmanagementteam** [comment]
This can wait.
