### ISSUE TITLE
[User feedback] Cross Sector Indicators and COVID Disaggregation

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#174]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
- Platform: Win32

## User report
URL: https://platform.samaritanspurse.org/api/apps/Data-Management-App/index.html#/projects/new

If a cross sector sub is chosen for COVID disaggregation... the corresponding global should also be selected for COVID (even if it's in a different sector).  Example- p020105 )cross sector sub) is selected yes for covid- p020100 (sector global) should also be selected yes for covid.  

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1596115355732319586.png )

**Comment by adrianq** [comment]
You are right we are not applying the dependency rule here. We will do so...
