### ISSUE TITLE
[User feedback] delete clarification- NOT URGENT

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#175]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
- Platform: Win32

## User report
URL: https://platform.samaritanspurse.org/api/apps/Data-Management-App/index.html#/

ORg units for a deleted project?  What happens if we need to delete projects in future?  Sorry- not bug but a question

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1596116526299544301.png )

**Comment by adrianq** [comment]
You can delete a project by right-clicking on the project and choose delete. This will delete all related metadata, i.e. datasets, dashboard, the org unit created for the project (not the country), etc. However, if there is already data introduced for this project a warning message will be shown to the user asking to contact the system admin. To delete data in DHIS2 is more tricky and we need to connect to the database and do it manually. We cannot delete the metadata of the project (datasets, dashboards, org units, etc) until the data has been deleted and, for now, the data deletion needs to be done by EST. Anyway, I think this action is not going be performed too often, right?
