### ISSUE TITLE
[User feedback] Different Funder- Same Award Code (subsequent lettering can have up to 3 characters)

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#184]
Subsequent lettering can have up to 3 characters. For example- 44444AAHQ and 44444AASC should be allowable

Original Issue:

## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Data-Management-App/index.html#/projects/new

I want the option to have the same award code and different funders for multiple projects.  For example, 11111AA (SP IHQ funded) and 11111AA (WFP funded) should be able to exist in the system. 

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1596570641836691687.png )

**Comment by jmatthewarnold** [comment]
Whoa! This is a big deal!  This goes back to a fundamental question: "What is a project?"  Let's discuss internally so that Adrian doesn't have to suffer through this.

**Comment by adrianq** [comment]
We have allowed the subsequent lettering to have 2 or 3 chars. However, this doesn't seem the requirement. @projectmanagementteam is checking internally how to proceed in this regard

**Comment by adrianq** [comment]
Finally, we will keep it as a  2 characters field for this release. We are having a deeper discussion regarding project coding and funders
