### ISSUE TITLE
[User feedback] Acronym for Funder

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#185]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Data-Management-App/index.html#/projects/new

Can we reduce the funder list?  Not urgent.
Can we associate an acronym with the funder name so it appears elsewhere?  Again- not urgent.  

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-159657085373512157.png )

**Comment by adrianq** [comment]
Sure, this is a 15 mins tasks. Can you copy the next version of the "Funder List" document in the Resources folder (https://drive.google.com/drive/u/0/folders/1hJ5LLOtOZLepGYcGRfrFytOV-l3TPNot)?

**Comment by adrianq** [comment]
Updated funder list: https://docs.google.com/spreadsheets/d/1M-vdHWIczDtff_JnCHMiYIhkmnLgWzHK/edit#gid=1128185203 Use columns A and D
