### ISSUE TITLE
[User feedback] Need to Select Custom Indicator

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#189]
## dhis2

Username: awarder

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36
- Platform: Win32

## User report
URL: https://platform.samaritanspurse.org/api/apps/Data-Management-App/index.html#/projects/edit/GlaVJdC6EA2

I need to be able to select this custom indicator to include in my MER.

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1597348602428817090.png )

**Comment by adrianq** [comment]
Duplicated of https://app.gitkraken.com/glo/view/card/f5429a06dbeb429aa431f23755324233 We will take care of this in the next release
