### ISSUE TITLE
[User feedback] 2nd page of usernames not showing all names

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#192]
## dhis2

Username: topelt

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
- Platform: Win32

## User report
URL: https://platform.samaritanspurse.org/api/apps/Data-Management-App/index.html#/

## Summary
there should be 3 names on 2nd page of users, but only 1 is showing up

## Expected results

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1598471825634379114.png )

**Comment by projectmanagementteam** [comment]
Yes- not urgent.  But, should be fixed.

**Comment by adrianq** [comment]
DHIS2 bug already reported:
https://jira.dhis2.org/browse/DHIS2-8863
https://jira.dhis2.org/browse/DHIS2-9454

**Comment by adrianq** [comment]
This has been fixed for DHIS2 versions 2.33 to 2.35. Unfortunately, 2.32  is not under maintenance anymore (see https://dhis2.org/downloads/). We will get advantage of this fix once we upgrade the DHIS2 version
