### ISSUE TITLE
[User feedback] Wrong Indicator Pairing

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#193]
## dhis2

Username: awarder

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
- Platform: Win32

## User report
URL: https://platform.samaritanspurse.org/api/apps/Data-Management-App/index.html#/target-values/hLT1oWjoXFq

The indicator # of kitchen kits provided should be paired with # of people provided with kitchen kits, however when I am attempting to enter target values it shows it pairing with # of people provided with clothing kits. Can you please correct this pairing?

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1598547867012804242.png )

**Comment by projectmanagementteam** [comment]
Yes- need to fix in indicator list.
