### ISSUE TITLE
[User feedback] MER Indicator Selection Error

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#199]
## dhis2

Username: pwoodside

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
- Platform: Win32

## User report
URL: https://platform.samaritanspurse.org/api/apps/Data-Management-App/index.html#/projects/edit/Twi5NfbpD8c

We are unable to select the debris removal indicators for the MER. PMT had to select those indicators once requested.

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-159924479835487494.png )

**Comment by projectmanagementteam** [comment]
Same comment as other custom indicator comment.

**Comment by adrianq** [comment]
Duplicated of 188
