### ISSUE TITLE
[User feedback] Buttons not working - Configure authorities for interpretations and messaging

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#20]
## dhis2

Username: rhanna

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
- Platform: Win32

## User report
URL: http://dev2.eyeseetea.com:8087/api/apps/Project-Monitoring-App/index.html#/

## Expected results

When I click these buttons I receive a 404 error message.
---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-158093130686062993.png )

**Comment by adrianq** [comment]
Duplicated issues:
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/26
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/65
