### ISSUE TITLE
[User feedback] Errors in MER: Show projects in last month of date

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#200]
## dhis2

Username: jkaimenyi

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36
- Platform: Win32

## User report
URL: https://platform.samaritanspurse.org/api/apps/Data-Management-App/index.html#/report

One of the projects (Emergency Livestock Flood Response) wasn’t reflecting on the August MER. We figured that it was because the project end date was set as 31st August in the system.
Upon changing the end date to September 30th, we then could view it in the MER. The actual end date is 31st August, so perhaps the system settings can be adjusted to allow report generation up to one or two months post end date?

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1599302081274845474.png )

**Comment by projectmanagementteam** [comment]
Yes- Adrian, is this behavior normal?  Can we please fix?

**Comment by adrianq** [comment]
It is a bug. Good catch! We will fix it  for the next version
