### ISSUE TITLE
[User feedback] Dashboard view- Scrolling with indicator statement viewable

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#205]
## dhis2

Username: kmuchiri

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36 Edg/85.0.564.51
- Platform: Win32

## User report
URL: https://platform.samaritanspurse.org/api/apps/Data-Management-App/index.html#/dashboard/uqVPMHk96uK

## Summary
Could it be possible to freeze columns with the indicator statements while scrolling right?
## Expected results

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1600062957674594006.png )

**Comment by projectmanagementteam** [comment]
Valid comment- is this possible?  While using dashboards, it would be helpful to always see the indicator while viewing months of data.
