### ISSUE TITLE
[User feedback] Location is Repeated in Column

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#208]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Data-Management-App/index.html#/report

The locations are repeated in the left column of the MER.  Can we have the location/s listed once and the corresponding projects under the location at that one place in the MER?

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-160035087988243343.png )

**Comment by adrianq** [comment]
Sure, this is clearly a bug!
