### ISSUE TITLE
[User feedback] not showing project list due to pagination issue

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#212]
## dhis2

Username: traindatareviewer

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-training.samaritanspurse.org/api/apps/Data-Management-App/index.html#/

## Summary
logged in as traindatareviewer, there should be 5-6 projects created by this user.  they are not visible on page 1, but can be found by clicking through to later pages, or by sorting on Last Updated column

## Expected results

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1601407706091402139.png )

**Comment by adrianq** [comment]
Yes, this is a bug. Looking into it!
