### ISSUE TITLE
[User feedback] Automatic User Access Issues

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#213]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
- Platform: Win32

## User report
URL: https://platform.samaritanspurse.org/api/apps/Data-Management-App/index.html#/projects/edit/cqZ9zQfePzQ

It looks like the admin groups are not automatically adding here... 

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1601578054803905806.png )

**Comment by jmatthewarnold** [comment]
Did you try scrolling down the list of who has access? Did you manually add the three at the bottom of the list (don’t see unless you scroll)?

Justin Arnold
SAMARITAN'S PURSE
Program Manager | Information Technology
828-588-2048 | Cell 828-406-1166 | jarnold@samaritan.org<mailto:jarnold@samaritan.org>
https://WWW.SAMARITANSPURSE.ORG <http://www.samaritanspurse.org/>
P.O. BOX 3000 | BOONE, NC 28607

**Comment by adrianq** [comment]
@projectmanagementteam I can see these three groups at very bottom as @jmatthewarnold pointed out. However, I cannot see the scroll bar on your screenshot. Did you do anything to fix this problem? Can you provide steps to reproduce otherwise?
![image](https://user-images.githubusercontent.com/6850223/94867827-e1085a00-0439-11eb-9fb4-9a90dcf88556.png)

**Comment by jmatthewarnold** [comment]
@projectmanagementteam, I saw this issue when you submitted it, but then when I checked for myself, the additional admin groups had been added.  I wanted to confirm that you added those – **is that correct?**  I see now (as @adrianq points out) that in the original screenshot, there was no scrollbar, which should indicate that the 4 users listed are the only ones with access and that the admin groups had not been added at that time.  Now that they are added there are enough users/groups listed that you have to scroll and thus the scroll bar appeared.

**Comment by adrianq** [comment]
Closing this after @projectmanagementteam confirming this is not a bug anymore
