### ISSUE TITLE
[User feedback] Question more than feedback

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#214]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Data-Management-App/index.html#/dashboard/YaVx7XoFRKm

Is there a way to download the tables/graphs to a pdf/image for report?  The button I used was not working.  

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1601664155694895943.png )

**Comment by adrianq** [comment]
@projectmanagementteam To download the whole dashboard to a pdf document is a feature only available in DHIS2 version 2.35. We are currently using version 2.32. We will eventually update the platform but this is not a minor migration/change and we will have to plan and schedule it with some time in advance. For now, you can click on the 'View in pivot table app' or 'View in visualizer app' button:
![image](https://user-images.githubusercontent.com/6850223/95051475-34ea9b80-06e5-11eb-8bff-52a04a7eb075.png)

and then download the chart or table in one of the available formats:
![image](https://user-images.githubusercontent.com/6850223/95051375-05d42a00-06e5-11eb-96e5-367ebf26a9a5.png)
