### ISSUE TITLE
[User feedback] Dashboard Indicator Codes

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#216]
## dhis2

Username: bwalker

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
- Platform: Win32

## User report
URL: https://platform.samaritanspurse.org/api/apps/Data-Management-App/index.html#/dashboard/TvSmIyYcRnd

## Summary
It would be great if we could add the feature to hover over the indicator description to see the indicator code to the dashboard. I know this feature was added to inputting 'actual data,' but it would be a helpful feature for the dashboard and data approval screens, too.
## Expected results

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1602253532433540764.png )

**Comment by dblalock-sp** [comment]
this is a comment by Derek
