### ISSUE TITLE
[User feedback] Add a contextual action in the country dashboard: "View users".  (for Data Reviewers)

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#220]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-training.samaritanspurse.org/api/apps/Data-Management-App/index.html#/

Modify the data reviewer username access to the following:	
Data Reviewer username (super user) only has access to usernames within the country office
o	Access includes:
-Viewing list of users per country (as well as seeing roles, group assignments, etc.)
-Editing the project access for users
-No access to create new usernames
-No access to delete usernames

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1603813881607200118.png )

**Comment by adrianq** [comment]
The only action point we have identified is to add a contextual action in the country dashboard: "View users". This action will open a dialog with a table listing  the users, user roles and user groups
