### ISSUE TITLE
[User feedback] Change "Speed Key" Name

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#222]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Data-Management-App/index.html#/projects/new

This seems to be confusing users.  Recommend changing "speed key" name.  Maybe, "Additional Classification," "Location/Sector Designation," etc.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1605195631842301477.png )

**Comment by adrianq** [comment]
Updated card with Betsy comments:
- [ ] Change name to: Additional Designation
- [ ] Need to update the instructions in the help button. Change to: - Additional Designation: In some instances, there are large projects that are split into multiple sectors or multiple locations for reporting. Use the ‘Additional Designation’ to designate different sectors or locations within the project. For example, if 11111AAHQ has three separate reporting sectors (11111AAHQ01, 11111AAHQ02, 11111AAHQ03), use the last two digits (01, 02, 03) in the ‘Additional Designation’ section.
