### ISSUE TITLE
Project Deletion

### ISSUE THREAD

**Issue by projectmanagementteam** [EyeSeeTea/SP-project-monitoring-app#254]
I need to delete two projects - 2699AI-SA and 5242AF. However, when I select delete it gives me an error message that says, "There are data values associated, the delete operation cannot be completed. Contact the administrators." Please advise.

**Comment by adrianq** [comment]
[data-2699AI-SA&5242AF.txt](https://app.gitkraken.com/api/glo/boards/5e38009c0e8c72001100f20b/attachments/60533c2f2ad1e30011227eae)
