### ISSUE TITLE
[User feedback] Code Column

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#3]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
- Platform: Win32

## User report
URL: http://dev2.eyeseetea.com:8087/api/apps/Project-Monitoring-App/index.html#/

## Summary
The code should have number portion first, and then lettering second.  Example- 99267SL
## Steps to reproduce
Change order.
## Expected results

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1580834340073425026.png )

**Comment by adrianq** [comment]
Duplicated issues:
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/27
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/29
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/61
