### ISSUE TITLE
[User feedback] Indicator Pairing

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#4]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
- Platform: Win32

## User report
URL: http://dev2.eyeseetea.com:8087/api/apps/Project-Monitoring-App/index.html#/projects/new

## Summary
If the sub benefit triggers the global benefit, then the corresponding global people should also be chosen.  So, in some scenarios, 2 indicators would populate with the selection of just one.
## Steps to reproduce
Pair subs with subs (For triggering).  Once the sub is chosen, both the global benefit and global people should populate.
## Expected results

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1580840247788928539.png )

**Comment by adrianq** [comment]
Duplicated issues:
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/32
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/35
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/36
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/37
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/38
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/40
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/41
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/58
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/68
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/69
