### ISSUE TITLE
[User feedback] setting actual values

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#5]
## dhis2

Username: topelt

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
- Platform: Win32

## User report
URL: http://dev2.eyeseetea.com:8087/api/apps/Project-Monitoring-App/index.html#/actual-values/AFSi7uxVU86

## Summary
reporting month opens up data entry boxes, but when i go to another month i can't get back into the original reporting month data entry screen
## Expected results

---
Note: Screenshots on sections dashboard and actual/target data entry will not be included, try to provide a detailed description of the problem.

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1580844462325652693.png )

**Comment by adrianq** [comment]
Duplicated issues:
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/23
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/39
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/62
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/63
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/76
https://github.com/EyeSeeTea/SP-project-monitoring-app/issues/77
