### ISSUE TITLE
[User feedback] Missing Sector Tabs

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/SP-project-monitoring-app#91]
## dhis2

Username: hlackey

## Browser
- Name: Mozilla
- Version: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
- Platform: Win32

## User report
URL: https://platform-test.samaritanspurse.org/api/apps/Project-Monitoring-App/index.html#/target-values/xkGTD940PxM

The data entry screen no longer has the sector data elements broken down by tabs. 

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1594054846507622555.png )

**Comment by adrianq** [comment]
Solved in 0.3.1
